--
-- Name: gpl3802_annotation; Type: TABLE; Schema: public; Owner: agrbrdf; Tablespace: 
--

CREATE TABLE gpl3802_annotation (
    probe_set_id character varying(30),
    genechip_array character varying(20),
    species_scientific_name character varying(20),
    annotation_date character varying(20),
    sequence_type character varying(20),
    sequence_source character varying(40),
    transcript_idarray_design character varying(20),
    target_description character varying(550),
    representative_public_id character varying(30),
    archival_unigene_cluster character varying(10),
    unigene_id character varying(50),
    genome_version character varying(10),
    alignments character varying(10),
    gene_title character varying(250),
    gene_symbol character varying(100),
    chromosomal_location character varying(10),
    unigene_cluster_type character varying(20),
    ensembl character varying(10),
    entrez_gene character varying(80),
    swissprot character varying(450),
    ec character varying(10),
    omim character varying(10),
    refseq_protein_id character varying(10),
    refseq_transcript_id character varying(10),
    flybase character varying(10),
    agi character varying(10),
    wormbase character varying(10),
    mgi_name character varying(10),
    rgd_name character varying(10),
    sgd_accession_number character varying(10),
    gene_ontology_biological_process character varying(1300),
    gene_ontology_cellular_component character varying(560),
    gene_ontology_molecular_function character varying(1660),
    pathway character varying(10),
    interpro character varying(350),
    trans_membrane character varying(580),
    qtl character varying(10),
    annotation_description character varying(200),
    annotation_transcript_cluster character varying(4140),
    transcript_assignments character varying(29950),
    annotation_notes character varying(15990),
    uniref_hit_accession__harvest_3over2010 character varying(100),
    uniref_hit_description__harvest_3over2010 character varying(170),
    uniref_e_value__harvest_3over2010 character varying(120),
    go_molecular_function_ids__agrigo_3over2010 character varying(160),
    go_molecular_function_terms__agrigo_3over2010 character varying(400),
    go_biological_process_ids__agrigo_3over2010 character varying(460),
    go_biological_process_terms__agrigo_3over2010 character varying(1190),
    go_cellular_component_ids__agrigo_3over2010 character varying(120),
    go_cellular_component_terms__agrigo_3over2010 character varying(200),
    go_missing_info_ids__agrigo_3over2010 character varying(30),
    go_missing_info_terms__agrigo_3over2010 character varying(40),
    datasourceob integer,
    voptypeid integer
);


ALTER TABLE public.gpl3802_annotation OWNER TO agrbrdf;

