--
-- Name: anneoconnelarrays2; Type: TABLE; Schema: public; Owner: agrbrdf; Tablespace: 
--

CREATE TABLE anneoconnelarrays2 (
    col integer,
    added character varying(10),
    differential character varying(30),
    probes character varying(30),
    probes_1 character varying(10),
    col_1 character varying(20),
    gene_id character varying(20),
    pubmatrix_submitted character varying(10),
    category character varying(140),
    gene_symbol character varying(20),
    est_length character varying(10),
    mean_intensity character varying(20),
    est1_w172_high double precision,
    est2_w230_high double precision,
    est3_w1215_high double precision,
    est4_w1276_high double precision,
    est5_w269_high double precision,
    est9_w156_neutral double precision,
    est6_w173_neutral double precision,
    est7_w209_low double precision,
    est10_w296_low double precision,
    est8_w1322_low double precision,
    df integer,
    n1 double precision,
    maximum double precision,
    stdev character varying(10),
    low character varying(10),
    high character varying(10),
    high_low character varying(10),
    res_sd double precision,
    dbias double precision,
    se1_w172 double precision,
    se2_w230 double precision,
    se3_w1215 double precision,
    se4_w1276 double precision,
    se5_w269 double precision,
    se6_w173 double precision,
    se7_w209 double precision,
    se8_w1322 double precision,
    se9_w156 double precision,
    se10_w296 double precision,
    cont1_low_vs_high double precision,
    fold_differnce_lowoverhigh_pct_mean double precision,
    high_versus_low double precision,
    secont1_low_vs_high double precision,
    tcont1_low_vs_high double precision,
    prcont1_low_vs_high double precision,
    modt_low_vs_high double precision,
    mod_sd_low_vs_high double precision,
    mod_pr_low_vs_high double precision,
    minuslogp_low_vs_high double precision,
    probes_2 character varying(20),
    datasourceob integer,
    voptypeid integer,
    dbprobes character varying(30)
);


ALTER TABLE public.anneoconnelarrays2 OWNER TO agrbrdf;

