--
-- Name: wheatchipannotation2011; Type: TABLE; Schema: public; Owner: agrbrdf; Tablespace: 
--

CREATE TABLE wheatchipannotation2011 (
    probeset character varying(30),
    log_ratio double precision,
    fold_change double precision,
    biological_fold_change double precision,
    absolute_biol_fold_change double precision,
    monad_3060_geomean integer,
    monad_e__geomean integer,
    maximum_geomean integer,
    moderated_p_value double precision,
    fdr double precision,
    logmod_p double precision,
    logfdr double precision,
    monad_3060_flag integer,
    monad_e__flag integer,
    mg0001_wheat_cel character varying(10),
    mg0003_wheat_cel character varying(10),
    mg0004_wheat_cel character varying(10),
    mg0005_wheat_cel character varying(10),
    mg0006_wheat_cel character varying(10),
    mg0007_wheat_cel character varying(10),
    monad_3060_pma_calls character varying(10),
    monad_e__pma_calls character varying(10),
    log_ratio_1 double precision,
    fold_change_1 double precision,
    biological_fold_change_1 double precision,
    absolute_biol_fold_change_1 double precision,
    monad_3060_geomean_1 integer,
    monad_e__geomean_1 integer,
    maximum_geomean_1 integer,
    moderated_p_value_1 double precision,
    fdr_1 double precision,
    logmod_p_1 double precision,
    logfdr_1 double precision,
    sequence_source character varying(40),
    transcript_idarray_design character varying(20),
    target_description character varying(550),
    representative_public_id character varying(30),
    representative_public_id_1 character varying(30),
    archival_unigene_cluster character varying(10),
    unigene_id character varying(50),
    unigene_id_1 character varying(50),
    genome_version character varying(10),
    alignments character varying(10),
    gene_title character varying(250),
    gene_symbol character varying(100),
    chromosomal_location character varying(10),
    unigene_cluster_type character varying(20),
    ensembl character varying(10),
    entrez_gene character varying(80),
    entrez_gene_1 character varying(80),
    swissprot character varying(390),
    gene_ontology_biological_process character varying(1300),
    gene_ontology_cellular_component character varying(630),
    gene_ontology_molecular_function character varying(1950),
    interpro character varying(350),
    trans_membrane character varying(760),
    annotation_description character varying(190),
    annotation_transcript_cluster character varying(4140),
    transcript_assignments character varying(29950),
    annotation_notes character varying(15990),
    uniref90_hit_accession__harvest_11over2010 character varying(100),
    uniref90_hit_accession__harvest_11over2010_1 character varying(100),
    uniref90_hit_description__harvest_11over2010 character varying(170),
    uniref90_e_value__harvest_11over2010 character varying(120),
    go_molecular_function_ids__agrigo_11over2010 character varying(160),
    go_molecular_function_terms__agrigo_11over2010 character varying(400),
    go_biological_process_ids__agrigo_11over2010 character varying(460),
    go_biological_process_terms__agrigo_11over2010 character varying(1190),
    go_cellular_component_ids__agrigo_11over2010 character varying(120),
    go_cellular_component_terms__agrigo_11over2010 character varying(200),
    go_missing_info_ids__agrigo_11over2010 character varying(30),
    go_missing_info_terms__agrigo_11over2010 character varying(40),
    probeid character varying(30),
    probe_set_name_found character varying(30),
    exemplar_assembly character varying(10),
    exemplar_unigene character varying(20),
    pre_polya_trim_length integer,
    members integer,
    num__unigenes integer,
    unigenes_represented character varying(910),
    uniprot_accn character varying(30),
    uniprot_e_score double precision,
    uniprot_desc character varying(170),
    rice_accn character varying(20),
    rice_e_score double precision,
    rice_chr integer,
    rice_5prime integer,
    rice_3prime integer,
    rice_desc character varying(130),
    arab_accn character varying(20),
    arab_e_score double precision,
    arab_chr character varying(10),
    arab_5prime integer,
    arab_3prime integer,
    arab_desc character varying(140),
    brachy_accn character varying(20),
    brachy_e_score double precision,
    brachy_chr character varying(10),
    brachy_5primepluscu3 integer,
    brachy_3prime integer,
    brachy_desc character varying(90),
    eof integer,
    datasourceob integer,
    voptypeid integer
);


ALTER TABLE public.wheatchipannotation2011 OWNER TO agrbrdf;

