#!/bin/bash
#
# run brdf on port (10000 + $UID)

CADDYFILE=$PWD/Caddyfile
CGIDIR=$PWD/cgi-bin
HTMLDIR=$PWD/html

test -r $CADDYFILE -a -r $CGIDIR -a -r $HTMLDIR || {
    echo >&2 "`basename $0`: must be run from top-level repo dir"
    exit 1
}

caddyport=$((10000 + $UID))
docker run --rm \
       --name brdf-$USER \
       --tmpfs /etc/caddycerts \
       --tmpfs /root/.caddy \
       --mount type=bind,src=$CADDYFILE,dst=/etc/Caddyfile \
       --mount type=bind,src=$CGIDIR,dst=/srv/cgi-bin \
       --mount type=bind,src=$HTMLDIR,dst=/srv/html \
       --tmpfs /srv/html/tmp \
       -p 10511:80 \
       agresearch/brdf
